# Generated by Django 4.2.3 on 2023-07-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_price"),
        ("users", "0004_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="courses_purchased",
            field=models.ManyToManyField(
                blank=True, related_name="purchased_by", to="courses.course"
            ),
        ),
    ]
